#Comments copied from: https://github.com/Gci04/AML-DS-2021/blob/main/.github/workflows/setup.yml
name: Environment set-up and NN models test

on:
 # Triggers the workflow on push or pull request events
 #push:
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.7' ## Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' ## Optional - x64 or x86 architecture, defaults to x64
        
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    # You can test your matrix by printing the current Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    
    - name: Train Model
      working-directory: ./src
      run: python train.py 
    - name: Test Model
      working-directory: ./src
      run: python test.py 
